export const Users = [
    {
      id:1,
      profilePicture: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
      username: "Sandeep Bhatt",
    },
    {
      id:2,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD8r54g86MEGRzywLkkTTu8CVFuhz3XdIGGA&usqp=CAU",
      username: "Saloni Bhatia",
    },
    {
      id:3,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLsupI89wVbXLRzxaiHG_rezqk3FrqDeMmog&usqp=CAU",
      username: "Akash yadav",
    },
    {
      id:4,
      profilePicture: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
      username: "Sachin",
    },
    {
      id:5,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLsupI89wVbXLRzxaiHG_rezqk3FrqDeMmog&usqp=CAU",
      username: "Vivek Singh",
    },
    {
      id:6,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD8r54g86MEGRzywLkkTTu8CVFuhz3XdIGGA&usqp=CAU",
      username: "Nishant Arora",
    },
    {
      id:7,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLsupI89wVbXLRzxaiHG_rezqk3FrqDeMmog&usqp=CAU",
      username: "Adi",
    },
    {
      id:8,
      profilePicture: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
      username: "Krishna kumar",
    },
    {
      id:9,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD8r54g86MEGRzywLkkTTu8CVFuhz3XdIGGA&usqp=CAU",
      username: "John Cena",
    },
    {
      id:10,
      profilePicture: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
      username: "Undertaker",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "https://raw.githubusercontent.com/safak/youtube/react-social-ui/public/assets/post/10.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      dislike:3,
      comment: 9,
    },
    {
      id: 2,
      photo: "https://raw.githubusercontent.com/safak/youtube/react-social-ui/public/assets/post/8.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      dislike:2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "https://raw.githubusercontent.com/safak/youtube/react-social-ui/public/assets/post/5.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      dislike:6,
      comment: 2,
    },
    {
      id: 4,
      photo: "https://raw.githubusercontent.com/safak/youtube/react-social-ui/public/assets/post/1.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      dislike:1,
      comment: 3,
    },
    {
      id: 5,
      photo: "https://raw.githubusercontent.com/safak/youtube/react-social-ui/public/assets/post/6.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      dislike:0,
      comment: 5,
    },
    {
      id: 6,
      photo: "https://raw.githubusercontent.com/safak/youtube/react-social-ui/public/assets/post/2.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      dislike:4,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "https://raw.githubusercontent.com/safak/youtube/react-social-ui/public/assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      dislike:5,
      comment: 3,
    },
    {
      id: 8,
      photo: "https://raw.githubusercontent.com/safak/youtube/react-social-ui/public/assets/post/9.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      dislike:1,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "https://raw.githubusercontent.com/safak/youtube/react-social-ui/public/assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      dislike:4,
      comment: 2,
    },
    {
      id: 10,
      photo: "https://raw.githubusercontent.com/safak/youtube/react-social-ui/public/assets/post/1.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      dislike:30,
      comment: 12,
    },
  ];